// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  homepage_hero: dynamic(() => import("./HomepageHero")),
};
